FROM ubuntu

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/mariorodvenUS/tcp_chat.git /app

WORKDIR /app/

RUN git pull 

WORKDIR /app/client/

RUN pip3 install -r requirements.txt

CMD ["python3", "client.py"]


