FROM ubuntu

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/mariorodvenUS/tcp_chat.git /app 

WORKDIR /app/server/

RUN git pull

RUN pip3 install termcolor

CMD python3 server_tcp.py


